'use client'
import {FormEvent,useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../../lib/supabase'
type Product={id:number;name:string;description:string;price:number;image_url:string|null;stock:number;is_active:boolean}
type Order={id:number;customer_name:string;customer_phone:string;customer_address:string;total:number;status:string;created_at:string}
export default function Admin(){
 const router=useRouter();const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [user,setUser]=useState('');const [form,setForm]=useState({name:'',description:'',price:'',stock:'',image_url:''})
 async function load(){const {data}=await supabase.auth.getUser();if(!data.user){router.replace('/admin/login');return}setUser(data.user.email||'');const p=await supabase.from('products').select('*').order('created_at',{ascending:false});setProducts(p.data||[]);const o=await supabase.from('orders').select('*').order('created_at',{ascending:false});setOrders(o.data||[])}
 useEffect(()=>{load()},[])
 async function add(e:FormEvent){e.preventDefault();const {error}=await supabase.from('products').insert({name:form.name,description:form.description,price:Number(form.price),stock:Number(form.stock),image_url:form.image_url||null,is_active:true});if(error)alert(error.message);else{setForm({name:'',description:'',price:'',stock:'',image_url:''});load()}}
 async function status(id:number,status:string){await supabase.from('orders').update({status}).eq('id',id);load()}
 async function logout(){await supabase.auth.signOut();router.replace('/admin/login')}
 return <main><nav className="nav"><b>Admin JualBeli</b><span>{user} <button className="btn secondary" onClick={logout}>Keluar</button></span></nav><div className="container"><div className="panel"><h2>Tambah Produk</h2><form onSubmit={add}><input className="input" placeholder="Nama produk" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Deskripsi" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="input" type="number" placeholder="Harga" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input className="input" type="number" placeholder="Stok" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input className="input" placeholder="URL foto produk" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><button className="btn">Simpan Produk</button></form></div><div className="panel"><h2>Produk ({products.length})</h2>{products.map(p=><div className="row" style={{justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid #eee'}} key={p.id}><span><b>{p.name}</b> — Rp {Number(p.price).toLocaleString('id-ID')} — stok {p.stock}</span></div>)}</div><div className="panel"><h2>Pesanan ({orders.length})</h2>{orders.map(o=><div style={{padding:'12px 0',borderBottom:'1px solid #eee'}} key={o.id}><b>#{o.id} {o.customer_name}</b><div>{o.customer_phone} · Rp {Number(o.total).toLocaleString('id-ID')}</div><small>{o.customer_address}</small><div className="row" style={{marginTop:8}}>{['pending','confirmed','packed','shipped','completed','cancelled'].map(s=><button key={s} className="btn secondary" onClick={()=>status(o.id,s)}>{s}</button>)}</div></div>)}</div></div></main>
}
