'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '../../lib/supabase'
type Product={id:number;name:string;description:string;price:number;image_url:string|null;stock:number;is_active:boolean}
type Order={id:number;customer_name:string;customer_phone:string;customer_address:string;total:number;status:string;created_at:string}
const statuses=['pending','confirmed','packed','shipped','completed','cancelled']
export default function Admin(){
 const router=useRouter(); const [products,setProducts]=useState<Product[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [user,setUser]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [imageFile,setImageFile]=useState<File|null>(null); const [preview,setPreview]=useState(''); const [error,setError]=useState(''); const [form,setForm]=useState({name:'',description:'',price:'',stock:'',image_url:''})
 async function load(){setLoading(true);setError('');const {data:auth}=await supabase.auth.getUser();if(!auth.user){router.replace('/admin/login');return}const {data:adminRow,error:adminError}=await supabase.from('admin_users').select('user_id').eq('user_id',auth.user.id).maybeSingle();if(adminError||!adminRow){await supabase.auth.signOut();router.replace('/admin/login?error=unauthorized');return}setUser(auth.user.email||'');const [{data:p,error:pError},{data:o,error:oError}]=await Promise.all([supabase.from('products').select('*').order('created_at',{ascending:false}),supabase.from('orders').select('*').order('created_at',{ascending:false})]);if(pError)setError(pError.message);if(oError)setError(oError.message);setProducts(p||[]);setOrders(o||[]);setLoading(false)}
 useEffect(()=>{load()},[]); useEffect(()=>{if(!imageFile){setPreview('');return}const url=URL.createObjectURL(imageFile);setPreview(url);return()=>URL.revokeObjectURL(url)},[imageFile])
 async function uploadImage(file:File){if(!file.type.startsWith('image/'))throw new Error('File harus berupa gambar.');if(file.size>5242880)throw new Error('Ukuran gambar maksimal 5 MB.');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path='products/'+crypto.randomUUID()+'.'+ext;const {error}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(error)throw error;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
 async function add(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{let imageUrl=form.image_url.trim()||null;if(imageFile)imageUrl=await uploadImage(imageFile);const {error}=await supabase.from('products').insert({name:form.name.trim(),description:form.description.trim(),price:Number(form.price),stock:Number(form.stock),image_url:imageUrl,is_active:true});if(error)throw error;setForm({name:'',description:'',price:'',stock:'',image_url:''});setImageFile(null);await load()}catch(err){setError(err instanceof Error?err.message:'Gagal menyimpan produk.')}finally{setSaving(false)}}
 async function toggleProduct(p:Product){const {error}=await supabase.from('products').update({is_active:!p.is_active}).eq('id',p.id);if(error)setError(error.message);else load()}
 async function deleteProduct(p:Product){if(!confirm('Hapus produk ini?'))return;const {error}=await supabase.from('products').delete().eq('id',p.id);if(error)setError(error.message);else load()}
 async function updateStatus(id:number,status:string){const {error}=await supabase.from('orders').update({status}).eq('id',id);if(error)setError(error.message);else load()}
 async function logout(){await supabase.auth.signOut();router.replace('/admin/login')}
 if(loading)return <main className="container"><p>Memuat dashboard...</p></main>
 return <main><nav className="nav"><b>Admin JualBeli</b><span>{user} <button className="btn secondary" onClick={logout}>Keluar</button></span></nav><div className="container">{error&&<div className="panel" style={{color:'crimson'}}>{error}</div>}<div className="panel"><h2>Tambah Produk</h2><form onSubmit={add}><input className="input" placeholder="Nama produk" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="input" placeholder="Deskripsi" rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="row"><input className="input" style={{flex:1,minWidth:180}} type="number" min="0" placeholder="Harga" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input className="input" style={{flex:1,minWidth:180}} type="number" min="0" placeholder="Stok" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></div><label>Foto produk (maks. 5 MB)</label><input className="input" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setImageFile(e.target.files?.[0]||null)}/>{preview&&<img src={preview} alt="Preview" style={{width:180,height:180,objectFit:'cover',borderRadius:12,marginBottom:12}}/>}<input className="input" placeholder="Atau URL foto produk" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><button className="btn" disabled={saving}>{saving?'Menyimpan...':'Simpan Produk'}</button></form></div><div className="panel"><h2>Produk ({products.length})</h2>{products.map(p=><div className="row" style={{justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid #eee'}} key={p.id}><span><b>{p.name}</b> — Rp {Number(p.price).toLocaleString('id-ID')} — stok {p.stock} — {p.is_active?'aktif':'nonaktif'}</span><span className="row"><button className="btn secondary" onClick={()=>toggleProduct(p)}>{p.is_active?'Nonaktifkan':'Aktifkan'}</button><button className="btn secondary" onClick={()=>deleteProduct(p)}>Hapus</button></span></div>)}</div><div className="panel"><h2>Pesanan ({orders.length})</h2>{orders.map(o=><div style={{padding:'12px 0',borderBottom:'1px solid #eee'}} key={o.id}><b>#{o.id} {o.customer_name}</b><div>{o.customer_phone} · Rp {Number(o.total).toLocaleString('id-ID')}</div><small>{o.customer_address}</small><div className="row" style={{marginTop:8}}>{statuses.map(s=><button key={s} className={o.status===s?'btn':'btn secondary'} onClick={()=>updateStatus(o.id,s)}>{s}</button>)}</div></div>)}</div></div></main>
}